name: Check build/run/tests

on:
  push:
    branches: [main]
  pull_request:
      # as by default
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Setting up dependencies
      run: |
        sudo apt install sox libsox-fmt-mp3 \
         libboost-filesystem-dev libcurl4-openssl-dev 
    - name: Setting up google-cloud-cpp
      run: |
        vcpkg install google-cloud-cpp[core,texttospeech]
    - name: Building target app
      run: |
        mkdir build && cd build &&
        cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake .. &&
        make -j $(nproc)
      
  execution:
    name: Execution
    #needs: [build]
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out 
      uses: actions/checkout@v4
    - name: Setting up dependencies
      run: |
        sudo apt install sox libsox-fmt-mp3 \
         libboost-filesystem-dev libcurl4-openssl-dev 
    - name: Setting up google-cloud-cpp
      run: |
        vcpkg install google-cloud-cpp[core,texttospeech]
    - name: Preparing binary
      run: |
        mkdir build && cd build &&
        cmake -DADD_EXAMPLES=ON -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake .. &&
        make -j $(nproc)
    - name: Executing googlebasic program
      run: |
        ./build/examples/googlebasic/googlebasic
    - name: Executing googleapi program
      run: |
        ./build/examples/googleapi/googleapi
    - name: Executing googlecloud program
      run: |
        ./build/examples/googlecloud/googlecloud 

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Setting up dependencies
      run: |
        sudo apt install sox libsox-fmt-mp3 \
         libboost-filesystem-dev libcurl4-openssl-dev 
    - name: Setting up google-cloud-cpp
      run: |
        vcpkg install google-cloud-cpp[core,texttospeech]
    - name: Building tests
      run: |
        cd tests && mkdir build && cd build && 
        cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake .. &&
        make -j $(nproc)
    - name: Running tests
      run: |
        ctest --output-on-failure --test-dir tests/build/

  tests-coverage:
    name: Coverage
    #needs: [test]
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Setting up dependencies
      run: |
        sudo apt install sox libsox-fmt-mp3 \
         libboost-filesystem-dev libcurl4-openssl-dev lcov
        cd tests && git clone https://github.com/lukaskaz/coverage-checker.git
    - name: Setting up google-cloud-cpp
      run: |
        vcpkg install google-cloud-cpp[core,texttospeech]
    - name: Preparing tests
      run: |
        cd tests && mkdir build && cd build &&
        cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake .. &&
        make -j $(nproc)
    - name: Running coverage checker
      run: |
        cd tests/coverage-checker && ./run.sh ../build
